import 'package:flutter/material.dart';import 'package:gymcito/core/app_export.dart';import 'package:gymcito/widgets/app_bar/custom_app_bar.dart';import 'package:gymcito/widgets/custom_outlined_button.dart';class FrameFourScreen extends StatelessWidget {const FrameFourScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 48.h, vertical: 4.v), child: Column(children: [SizedBox(height: 507.v, width: 291.h, child: Stack(alignment: Alignment.topLeft, children: [Align(alignment: Alignment.topCenter, child: SizedBox(width: 224.h, child: Text("Que Entrenaras Hoy?", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.headlineMedium!.copyWith(height: 1.10)))), Padding(padding: EdgeInsets.only(left: 6.h, top: 70.v), child: _buildTitle(context, userImage: ImageConstant.imgRectangle313120x136, userName: "PECHO")), Padding(padding: EdgeInsets.only(right: 3.h, bottom: 145.v), child: _buildTitle(context, userImage: ImageConstant.imgRectangle3131, userName: "BRAZO")), Padding(padding: EdgeInsets.only(bottom: 145.v), child: _buildTitle(context, userImage: ImageConstant.imgRectangle3132, userName: "ESPALDA")), _buildTitle(context, userImage: ImageConstant.imgRectangle3133, userName: "PIERNA"), Padding(padding: EdgeInsets.only(left: 6.h), child: _buildTitle(context, userImage: ImageConstant.imgRectangle3134, userName: "HOMBRO")), Padding(padding: EdgeInsets.only(top: 70.v, right: 3.h), child: _buildTitle(context, userImage: ImageConstant.imgRectangle3135, userName: "ABDOMEN"))])), SizedBox(height: 6.v), CustomImageView(imagePath: ImageConstant.imgRectangle313120x285, height: 120.v, width: 285.h, radius: BorderRadius.circular(4.h)), SizedBox(height: 5.v), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 111.h), child: Text("Mas.....", style: CustomTextStyles.titleSmallPoppinsWhiteA700)))])), bottomNavigationBar: _buildContinuar(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 34.h, leading: Container(height: 23.v, width: 14.h, margin: EdgeInsets.only(left: 20.h, top: 16.v, bottom: 16.v), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 23.v, width: 14.h, alignment: Alignment.center, onTap: () {onTapImgArrowLeft(context);}), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 23.v, width: 14.h, alignment: Alignment.center)])), actions: [Padding(padding: EdgeInsets.symmetric(horizontal: 53.h, vertical: 16.v), child: Column(children: [Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h)))]))]); } 
/// Section Widget
Widget _buildContinuar(BuildContext context) { return CustomOutlinedButton(height: 72.v, text: "Continuar", margin: EdgeInsets.only(left: 37.h, right: 27.h, bottom: 40.v), rightIcon: Container(margin: EdgeInsets.only(), decoration: BoxDecoration(borderRadius: BorderRadius.circular(15.h)), child: CustomImageView(imagePath: ImageConstant.imgBg, height: 72.v, width: 328.h)), buttonStyle: CustomButtonStyles.outlineBlackTL151); } 
/// Common widget
Widget _buildTitle(BuildContext context, {required String userImage, required String userName, }) { return Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: userImage, height: 120.v, width: 136.h, radius: BorderRadius.circular(4.h)), SizedBox(height: 3.v), Padding(padding: EdgeInsets.only(left: 35.h), child: Text(userName, style: CustomTextStyles.titleSmallPoppinsWhiteA700.copyWith(color: appTheme.whiteA700)))]); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
