import 'package:flutter/material.dart';import 'package:gymcito/core/app_export.dart';import 'package:gymcito/widgets/app_bar/appbar_leading_image.dart';import 'package:gymcito/widgets/app_bar/custom_app_bar.dart';import 'package:gymcito/widgets/custom_outlined_button.dart';import 'package:gymcito/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class Userdata52Screen extends StatelessWidget {Userdata52Screen({Key? key}) : super(key: key);

TextEditingController group110Controller = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 50.h, vertical: 32.v), child: Column(children: [SizedBox(width: 170.h, child: RichText(text: TextSpan(children: [TextSpan(text: "cual es tu forma corporal ", style: CustomTextStyles.titleLargePoppins), TextSpan(text: "acutal?", style: CustomTextStyles.titleLargePoppinsPrimary)]), textAlign: TextAlign.center)), SizedBox(height: 32.v), CustomImageView(imagePath: ImageConstant.imgRectangle315, height: 155.v, width: 219.h, radius: BorderRadius.circular(8.h)), SizedBox(height: 35.v), Container(margin: EdgeInsets.only(right: 3.h), padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 11.v), decoration: AppDecoration.fillLimeA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder24), child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeftWhiteA700, height: 23.v, width: 14.h, margin: EdgeInsets.only(left: 9.h), onTap: () {onTapImgArrowLeft(context);}), Spacer(flex: 44), Text("Elige tu fisico Actual", style: CustomTextStyles.titleMediumSourceSansPro), Spacer(flex: 55), CustomImageView(imagePath: ImageConstant.imgArrowRight, height: 23.v, width: 15.h)])), SizedBox(height: 28.v), Container(margin: EdgeInsets.only(right: 3.h), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.circleBorder16), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomTextFormField(controller: group110Controller, hintText: "Tu grasa corporal aproximada es de : ", textInputAction: TextInputAction.done, contentPadding: EdgeInsets.symmetric(horizontal: 13.h, vertical: 14.v), borderDecoration: TextFormFieldStyleHelper.fillGray, fillColor: appTheme.gray400), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(left: 13.h), child: Text("% 15 - 20 % (Alta)", style: CustomTextStyles.titleSmallPrimary)), SizedBox(height: 17.v), Container(width: 243.h, margin: EdgeInsets.only(left: 13.h, right: 33.h), child: Text("Tu porcentaje de grasa es alto,no te preocupes,te daremos la dieta y ejercicios adecuados para alcanzar tu objetivo.", maxLines: 3, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumSourceSansProBlack900.copyWith(height: 2.21))), SizedBox(height: 9.v)])), SizedBox(height: 5.v)])), bottomNavigationBar: _buildContinuar(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 44.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 30.h, top: 16.v, bottom: 16.v), onTap: () {onTapArrowLeft(context);}), actions: [Padding(padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 16.v), child: Column(children: [Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h)))]))]); } 
/// Section Widget
Widget _buildContinuar(BuildContext context) { return CustomOutlinedButton(text: "Continuar", margin: EdgeInsets.only(left: 50.h, right: 51.h, bottom: 56.v), buttonStyle: CustomButtonStyles.outlineBlackTL22, onPressed: () {onTapContinuar(context);}); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the userdatafiveScreen when the action is triggered.
onTapImgArrowLeft(BuildContext context) { Navigator.pushNamed(context, AppRoutes.userdatafiveScreen); } 
/// Navigates to the noti1Screen when the action is triggered.
onTapContinuar(BuildContext context) { Navigator.pushNamed(context, AppRoutes.noti1Screen); } 
 }
