import 'package:flutter/material.dart';import 'package:gymcito/core/app_export.dart';import 'package:gymcito/widgets/app_bar/appbar_leading_image.dart';import 'package:gymcito/widgets/app_bar/custom_app_bar.dart';import 'package:gymcito/widgets/custom_outlined_button.dart';class Noti1Screen extends StatelessWidget {const Noti1Screen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 42.h, vertical: 23.v), child: Column(children: [SizedBox(height: 338.v, width: 252.h, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: Text("Objetivos", style: CustomTextStyles.titleLargePoppinsPrimaryBold)), CustomImageView(imagePath: ImageConstant.imgPngwing2, height: 318.v, width: 252.h, alignment: Alignment.bottomCenter)])), SizedBox(height: 26.v), Text("¡ Ya Casi Terminamos!", style: CustomTextStyles.headlineLargeSourceSansProBold), SizedBox(height: 14.v), Container(width: 237.h, margin: EdgeInsets.only(left: 34.h, right: 35.h), child: Text("Una vez terminados todos los pasos recopilaremos tus datos poara poder brindarte la mejor dieta y enternamiento que se adecue a tus objetivos", maxLines: 4, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumSourceSansPro.copyWith(height: 2.21))), SizedBox(height: 5.v)])), bottomNavigationBar: _buildContinuar(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 44.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 30.h, top: 16.v, bottom: 16.v), onTap: () {onTapArrowLeft(context);}), actions: [Padding(padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 16.v), child: Column(children: [Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h)))]))]); } 
/// Section Widget
Widget _buildContinuar(BuildContext context) { return CustomOutlinedButton(text: "Continuar", margin: EdgeInsets.only(left: 50.h, right: 51.h, bottom: 56.v), buttonStyle: CustomButtonStyles.outlineBlackTL22, onPressed: () {onTapContinuar(context);}); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the userdatasixTabContainerScreen when the action is triggered.
onTapContinuar(BuildContext context) { Navigator.pushNamed(context, AppRoutes.userdatasixTabContainerScreen); } 
 }
