import 'package:flutter/material.dart';import 'package:gymcito/core/app_export.dart';import 'package:gymcito/widgets/app_bar/custom_app_bar.dart';class Iphone1415Pro118Screen extends StatelessWidget {const Iphone1415Pro118Screen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(height: 696.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: Container(decoration: AppDecoration.outlineBlack, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [_buildArrowLeftRow(context), SizedBox(height: 27.v), Padding(padding: EdgeInsets.only(left: 22.h), child: Text("Datos", style: theme.textTheme.displayMedium)), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(left: 22.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 11.v, width: 13.h, margin: EdgeInsets.only(top: 1.v, bottom: 7.v), decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(6.h))), Padding(padding: EdgeInsets.only(left: 13.h), child: Text("Mejora de la postura", style: CustomTextStyles.titleMediumMontserratBluegray10003))])), SizedBox(height: 9.v), Padding(padding: EdgeInsets.only(left: 22.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 11.v, width: 13.h, margin: EdgeInsets.only(top: 1.v, bottom: 7.v), decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(6.h))), Padding(padding: EdgeInsets.only(left: 13.h), child: Text("Trabajo cardiovascular", style: CustomTextStyles.titleMediumMontserratBluegray10003))])), SizedBox(height: 7.v), Padding(padding: EdgeInsets.only(left: 22.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 11.v, width: 13.h, margin: EdgeInsets.only(top: 3.v, bottom: 26.v), decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(6.h))), Container(width: 228.h, margin: EdgeInsets.only(left: 13.h), child: Text("Trabajo de múltiples grupos musculares", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleMediumMontserratBluegray10003))])), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(left: 22.h, right: 90.h), child: Row(children: [Container(height: 11.v, width: 13.h, margin: EdgeInsets.only(top: 5.v, bottom: 4.v), decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(6.h))), Padding(padding: EdgeInsets.only(left: 10.h), child: Text("Aumento de la fuerza funcional", style: CustomTextStyles.titleMediumMontserratBluegray10003))])), SizedBox(height: 6.v)]))), _buildNavigationBar(context), _buildHomeRow(context)])), bottomNavigationBar: _buildBottomBar(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 73.v, leadingWidth: 58.h, leading: Container(height: 23.v, width: 14.h, margin: EdgeInsets.only(left: 44.h), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 23.v, width: 14.h, alignment: Alignment.center, onTap: () {onTapImgArrowLeft(context);}), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 23.v, width: 14.h, alignment: Alignment.center)])), actions: [Padding(padding: EdgeInsets.symmetric(horizontal: 29.h), child: Column(children: [Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h)))]))]); } 
/// Section Widget
Widget _buildArrowLeftRow(BuildContext context) { return Container(width: double.maxFinite, decoration: AppDecoration.fillGreen, child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 51.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 23.v, width: 14.h, margin: EdgeInsets.only(left: 40.h), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 23.v, width: 14.h, alignment: Alignment.center, onTap: () {onTapImgArrowLeft1(context);}), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 23.v, width: 14.h, alignment: Alignment.center)])), SizedBox(height: 26.v), Align(alignment: Alignment.centerRight, child: Container(height: 53.v, width: 60.h, decoration: BoxDecoration(borderRadius: BorderRadius.circular(30.h), gradient: LinearGradient(begin: Alignment(0.23, 0.05), end: Alignment(0.65, 0.7), colors: [appTheme.whiteA700.withOpacity(0.18), appTheme.whiteA700.withOpacity(0.18)])))), SizedBox(height: 164.v), Container(height: 66.v, width: 86.h, decoration: BoxDecoration(gradient: LinearGradient(begin: Alignment(0.5, 0), end: Alignment(0.5, 1), colors: [appTheme.whiteA700.withOpacity(0.17), appTheme.whiteA700.withOpacity(0)])))])), Spacer(flex: 38), Padding(padding: EdgeInsets.only(top: 47.v, bottom: 306.v), child: Text("Ejercicio ", style: CustomTextStyles.headlineSmallMontserratBluegray50)), Spacer(flex: 61), Container(margin: EdgeInsets.only(bottom: 262.v), padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 48.v), decoration: AppDecoration.gradientWhiteAToWhiteA, child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h)))]))])); } 
/// Section Widget
Widget _buildNavigationBar(BuildContext context) { return Align(alignment: Alignment.bottomCenter, child: Container(decoration: AppDecoration.fillOnSecondaryContainer, child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 96.v), Divider()]))); } 
/// Section Widget
Widget _buildHomeRow(BuildContext context) { return Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(left: 31.h, top: 703.v, right: 41.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgHome, height: 42.v, width: 41.h), Spacer(flex: 33), CustomImageView(imagePath: ImageConstant.imgActivity, height: 26.adaptSize, width: 26.adaptSize, margin: EdgeInsets.symmetric(vertical: 7.v), onTap: () {onTapImgActivity(context);}), Spacer(flex: 41), CustomImageView(imagePath: ImageConstant.imgTelevision, height: 32.v, width: 37.h, margin: EdgeInsets.only(top: 5.v, bottom: 4.v)), Spacer(flex: 24), CustomImageView(imagePath: ImageConstant.imgUser, height: 42.v, width: 41.h)]))); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return Container(decoration: BoxDecoration(color: theme.colorScheme.onSecondaryContainer), child: Padding(padding: EdgeInsets.only(bottom: 79.v), child: SizedBox(width: 392.h, child: Divider()))); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft1(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the iphone1415ProTenScreen when the action is triggered.
onTapImgActivity(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone1415ProTenScreen); } 
 }
