import 'package:flutter/material.dart';import 'package:gymcito/core/app_export.dart';import 'package:gymcito/widgets/app_bar/custom_app_bar.dart';import 'package:gymcito/widgets/custom_outlined_button.dart';class Userdata31Screen extends StatelessWidget {const Userdata31Screen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 38.h, vertical: 30.v), child: Column(children: [Container(width: 247.h, margin: EdgeInsets.only(left: 36.h, right: 32.h), child: Text("¿Cuál es tu nivel de actividad física regular?", maxLines: 3, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.headlineSmallPoppinsWhiteA700.copyWith(height: 1.20))), SizedBox(height: 17.v), Text("Esto nos ayuda a crear tu plan personalizado.", style: CustomTextStyles.labelLargePoppinsWhiteA700), Spacer(flex: 56), Text("Intermediante", style: CustomTextStyles.headlineMediumOpenSans), SizedBox(height: 17.v), Align(alignment: Alignment.centerRight, child: Divider(color: theme.colorScheme.primary, indent: 43.h, endIndent: 27.h)), SizedBox(height: 22.v), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 84.h), child: Text("Avanzado", style: CustomTextStyles.headlineMediumOpenSans))), SizedBox(height: 16.v), Align(alignment: Alignment.centerRight, child: Divider(color: theme.colorScheme.primary, indent: 43.h, endIndent: 27.h)), SizedBox(height: 15.v), Text("Bestia", style: CustomTextStyles.headlineSmallOpenSansWhiteA700), SizedBox(height: 10.v), Text("Principiante", style: CustomTextStyles.titleLargeOpenSansGray800), Spacer(flex: 43), SizedBox(height: 24.v), CustomOutlinedButton(text: "Continuar", margin: EdgeInsets.only(left: 22.h, right: 3.h), buttonStyle: CustomButtonStyles.outlineGray, alignment: Alignment.centerRight)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 55.h, leading: Container(height: 34.v, width: 17.h, margin: EdgeInsets.only(left: 38.h, top: 10.v, bottom: 11.v), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeftGray900, height: 23.v, width: 14.h, alignment: Alignment.center, margin: EdgeInsets.only(top: 11.v, right: 3.h), onTap: () {onTapImgArrowLeft(context);}), CustomImageView(imagePath: ImageConstant.imgArrowLeftGray900, height: 23.v, width: 14.h, alignment: Alignment.center, margin: EdgeInsets.only(top: 11.v, right: 3.h)), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 23.v, width: 14.h, alignment: Alignment.center, margin: EdgeInsets.only(left: 3.h, bottom: 11.v), onTap: () {onTapImgArrowLeft1(context);}), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 23.v, width: 14.h, alignment: Alignment.center, margin: EdgeInsets.only(left: 3.h, bottom: 11.v))])), actions: [Padding(padding: EdgeInsets.fromLTRB(32.h, 10.v, 32.h, 11.v), child: Column(children: [Align(alignment: Alignment.centerRight, child: Container(height: 5.v, width: 30.h, margin: EdgeInsets.only(left: 4.h), decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h)))), SizedBox(height: 4.v), Align(alignment: Alignment.centerRight, child: Container(height: 5.v, width: 30.h, margin: EdgeInsets.only(left: 4.h), decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h)))), SizedBox(height: 4.v), SizedBox(height: 7.v, width: 34.h, child: Stack(alignment: Alignment.topRight, children: [Align(alignment: Alignment.bottomLeft, child: Container(height: 5.v, width: 30.h, margin: EdgeInsets.only(top: 2.v, right: 4.h), decoration: BoxDecoration(color: appTheme.gray900, borderRadius: BorderRadius.circular(2.h)))), Align(alignment: Alignment.topRight, child: Container(height: 5.v, width: 30.h, margin: EdgeInsets.only(left: 4.h, bottom: 2.v), decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))))])), SizedBox(height: 4.v), Align(alignment: Alignment.centerLeft, child: Container(height: 5.v, width: 30.h, margin: EdgeInsets.only(right: 4.h), decoration: BoxDecoration(color: appTheme.gray900, borderRadius: BorderRadius.circular(2.h))))]))]); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft1(BuildContext context) { Navigator.pop(context); } 
 }
