import 'package:flutter/material.dart';import 'package:gymcito/core/app_export.dart';import 'package:gymcito/widgets/custom_outlined_button.dart';class Noti3Screen extends StatelessWidget {const Noti3Screen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 51.v), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 5.v), Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 23.v, width: 14.h, margin: EdgeInsets.only(bottom: 721.v), onTap: () {onTapImgArrowLeft(context);}), Expanded(child: Padding(padding: EdgeInsets.only(left: 6.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.centerRight, child: Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h)))), SizedBox(height: 4.v), Align(alignment: Alignment.centerRight, child: Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h)))), SizedBox(height: 4.v), Align(alignment: Alignment.centerRight, child: Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h)))), Spacer(), Padding(padding: EdgeInsets.only(left: 78.h), child: Text("¡Todo Listo!", style: CustomTextStyles.headlineMediumSourceSansProLimeA400)), SizedBox(height: 25.v), Container(width: 264.h, margin: EdgeInsets.only(left: 18.h, right: 30.h), child: RichText(text: TextSpan(children: [TextSpan(text: "En breve tendremos tu Plan de entrenamiento ademas de una  dieta especifica que se adecue a tus requerimientos y propositos,sigue adelante y empecemos con el reto", style: CustomTextStyles.bodyMediumSourceSansPro_2), TextSpan(text: "!", style: CustomTextStyles.labelLargeSourceSansProWhiteA700Bold)]), textAlign: TextAlign.center)), SizedBox(height: 33.v), CustomOutlinedButton(text: "Continuar", margin: EdgeInsets.only(right: 22.h), onPressed: () {onTapContinuar(context);})])))])])))); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the iphone1415ProRutinaPrincipianteTabContainerScreen when the action is triggered.
onTapContinuar(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone1415ProRutinaPrincipianteTabContainerScreen); } 
 }
