import 'package:flutter/material.dart';import 'package:gymcito/core/app_export.dart';import 'package:gymcito/widgets/app_bar/custom_app_bar.dart';class Iphone1415ProSixteenScreen extends StatelessWidget {const Iphone1415ProSixteenScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(height: 696.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: Container(decoration: AppDecoration.outlineBlack, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [_buildAnalysisOfFoods(context), SizedBox(height: 14.v), Padding(padding: EdgeInsets.only(left: 22.h), child: Text("Contiene", style: theme.textTheme.displayMedium)), SizedBox(height: 15.v), _buildFoodComposition(context), SizedBox(height: 4.v), _buildNutritionInformation(context), SizedBox(height: 4.v)]))), _buildNavigationBar(context), _buildHomeScreen(context)])), bottomNavigationBar: _buildBottomBar(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 73.v, leadingWidth: 58.h, leading: Container(height: 23.v, width: 14.h, margin: EdgeInsets.only(left: 44.h), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 23.v, width: 14.h, alignment: Alignment.center, onTap: () {onTapImgArrowLeft(context);}), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 23.v, width: 14.h, alignment: Alignment.center)])), actions: [Padding(padding: EdgeInsets.symmetric(horizontal: 29.h), child: Column(children: [Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h)))]))]); } 
/// Section Widget
Widget _buildAnalysisOfFoods(BuildContext context) { return Container(height: 396.v, width: double.maxFinite, decoration: AppDecoration.fillGreen, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: Container(width: 138.h, margin: EdgeInsets.only(top: 45.v), child: Text("Análisis de alimentos ", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.headlineSmallMontserratBluegray50.copyWith(height: 1.87)))), Align(alignment: Alignment.bottomCenter, child: Container(height: 247.v, width: 276.h, margin: EdgeInsets.only(bottom: 30.v), decoration: BoxDecoration(borderRadius: BorderRadius.circular(138.h), gradient: LinearGradient(begin: Alignment(0.5, 0), end: Alignment(0.4, 1), colors: [appTheme.black900.withOpacity(0.18), appTheme.whiteA700.withOpacity(0.18)])))), CustomImageView(imagePath: ImageConstant.imgImagePlaceholder, height: 164.v, width: 278.h, alignment: Alignment.bottomRight, margin: EdgeInsets.only(right: 31.h, bottom: 87.v)), Align(alignment: Alignment.topLeft, child: Container(height: 53.v, width: 60.h, margin: EdgeInsets.only(left: 48.h, top: 101.v), decoration: BoxDecoration(borderRadius: BorderRadius.circular(30.h), gradient: LinearGradient(begin: Alignment(0.23, 0.05), end: Alignment(0.65, 0.7), colors: [appTheme.whiteA700.withOpacity(0.18), appTheme.whiteA700.withOpacity(0.18)])))), Align(alignment: Alignment.topRight, child: Container(padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 48.v), decoration: AppDecoration.gradientWhiteAToWhiteA, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h)))]))), Align(alignment: Alignment.bottomLeft, child: Container(height: 66.v, width: 86.h, margin: EdgeInsets.only(bottom: 12.v), decoration: BoxDecoration(gradient: LinearGradient(begin: Alignment(0.5, 0), end: Alignment(0.5, 1), colors: [appTheme.whiteA700.withOpacity(0.17), appTheme.whiteA700.withOpacity(0)])))), Align(alignment: Alignment.topLeft, child: Container(height: 23.v, width: 14.h, margin: EdgeInsets.only(left: 40.h, top: 51.v), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 23.v, width: 14.h, alignment: Alignment.center, onTap: () {onTapImgArrowLeft1(context);}), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 23.v, width: 14.h, alignment: Alignment.center)])))])); } 
/// Section Widget
Widget _buildFoodComposition(BuildContext context) { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.only(left: 22.h, right: 31.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 11.v, width: 13.h, margin: EdgeInsets.only(top: 2.v, bottom: 10.v), decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(6.h))), Padding(padding: EdgeInsets.only(left: 12.h, bottom: 4.v), child: Text("Vitamina C", style: CustomTextStyles.titleMediumMontserratBluegray10003)), Spacer(), Container(height: 11.v, width: 13.h, margin: EdgeInsets.only(top: 2.v, bottom: 10.v), decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(6.h))), Padding(padding: EdgeInsets.only(left: 27.h, top: 4.v), child: Text("2 gram fiber", style: CustomTextStyles.titleMediumMontserratBluegray10003))]))); } 
/// Section Widget
Widget _buildNutritionInformation(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 22.h, right: 36.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(width: 214.h, child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 11.v, width: 13.h, margin: EdgeInsets.only(top: 2.v, bottom: 6.v), decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(6.h))), Padding(padding: EdgeInsets.only(left: 13.h), child: Text("32 calorias", style: CustomTextStyles.titleMediumMontserratBluegray10003)), Spacer(), Container(height: 12.v, width: 13.h, margin: EdgeInsets.only(top: 6.v), decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(6.h)))])), SizedBox(height: 9.v), Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 11.v, width: 13.h, margin: EdgeInsets.only(top: 2.v, bottom: 29.v), decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(6.h))), Container(width: 114.h, margin: EdgeInsets.only(left: 13.h), child: Text("0.7 gramos de proteina", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleMediumMontserratBluegray10003))])]), Container(width: 90.h, margin: EdgeInsets.only(left: 30.h, top: 3.v, bottom: 25.v), child: Text("4.9 gramos azugar", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleMediumMontserratBluegray10003))])); } 
/// Section Widget
Widget _buildNavigationBar(BuildContext context) { return Align(alignment: Alignment.bottomCenter, child: Container(decoration: AppDecoration.fillOnSecondaryContainer, child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 79.v), Divider()]))); } 
/// Section Widget
Widget _buildHomeScreen(BuildContext context) { return Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(left: 32.h, top: 720.v, right: 40.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgHome, height: 42.v, width: 41.h, onTap: () {onTapImgHome(context);}), Spacer(flex: 33), CustomImageView(imagePath: ImageConstant.imgActivity, height: 26.adaptSize, width: 26.adaptSize, margin: EdgeInsets.symmetric(vertical: 7.v), onTap: () {onTapImgActivity(context);}), Spacer(flex: 41), CustomImageView(imagePath: ImageConstant.imgTelevision, height: 32.v, width: 37.h, margin: EdgeInsets.only(bottom: 9.v)), Spacer(flex: 25), CustomImageView(imagePath: ImageConstant.imgUser, height: 42.v, width: 41.h)]))); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return Container(decoration: BoxDecoration(color: theme.colorScheme.onSecondaryContainer), child: Padding(padding: EdgeInsets.only(bottom: 79.v), child: SizedBox(width: 392.h, child: Divider()))); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft1(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the iphone1415ProRutinaPrincipianteTabContainerScreen when the action is triggered.
onTapImgHome(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone1415ProRutinaPrincipianteTabContainerScreen); } 
/// Navigates to the iphone1415ProTenScreen when the action is triggered.
onTapImgActivity(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone1415ProTenScreen); } 
 }
