import '../iphone_14_15_pro_twentytwo_screen/widgets/cardlist_item_widget.dart';import 'package:flutter/material.dart';import 'package:gymcito/core/app_export.dart';import 'package:gymcito/widgets/app_bar/appbar_leading_image.dart';import 'package:gymcito/widgets/app_bar/custom_app_bar.dart';import 'package:gymcito/widgets/custom_outlined_button.dart';class Iphone1415ProTwentytwoScreen extends StatelessWidget {const Iphone1415ProTwentytwoScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 39.h, vertical: 29.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 188.h, margin: EdgeInsets.only(left: 53.h), child: Text("cual es tu objetivo principal?", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleLargePoppinsBold.copyWith(height: 1.54))), SizedBox(height: 31.v), Row(children: [SizedBox(height: 456.v, width: 292.h, child: Stack(alignment: Alignment.centerRight, children: [_buildCardList(context), Align(alignment: Alignment.centerRight, child: Column(mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.only(right: 2.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(width: 85.h, margin: EdgeInsets.only(top: 42.v, bottom: 36.v), child: Text("Perdida de \nPeso", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleSmallPoppins.copyWith(height: 1.25))), CustomImageView(imagePath: ImageConstant.imgRectangle315120x158, height: 120.v, width: 158.h, radius: BorderRadius.circular(8.h), margin: EdgeInsets.only(left: 21.h))])), SizedBox(height: 55.v), CustomImageView(imagePath: ImageConstant.imgRectangle314, height: 120.v, width: 156.h, radius: BorderRadius.circular(8.h), alignment: Alignment.centerRight, margin: EdgeInsets.only(right: 5.h)), SizedBox(height: 41.v), Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(width: 81.h, margin: EdgeInsets.only(top: 39.v, bottom: 41.v), child: Text("Aumentar Musculo", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleSmallPoppins.copyWith(height: 1.25))), CustomImageView(imagePath: ImageConstant.imgRectangle313, height: 120.v, width: 153.h, radius: BorderRadius.circular(8.h), margin: EdgeInsets.only(left: 32.h))])])), Align(alignment: Alignment.centerLeft, child: Container(width: 95.h, margin: EdgeInsets.only(left: 18.h), child: Text("Mantenerse\nen Forma", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleSmallPoppins.copyWith(height: 1.25))))])), Padding(padding: EdgeInsets.only(left: 5.h, top: 312.v, bottom: 119.v), child: Text("16", style: CustomTextStyles.titleSmallPoppins))]), SizedBox(height: 5.v)])), bottomNavigationBar: _buildContinueButton(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 44.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 30.h, top: 16.v, bottom: 16.v), onTap: () {onTapArrowLeft(context);}), actions: [Padding(padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 16.v), child: Column(children: [Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h)))]))]); } 
/// Section Widget
Widget _buildCardList(BuildContext context) { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.only(right: 2.h), child: ListView.separated(physics: BouncingScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 55.v);}, itemCount: 3, itemBuilder: (context, index) {return CardlistItemWidget();}))); } 
/// Section Widget
Widget _buildContinueButton(BuildContext context) { return CustomOutlinedButton(text: "Continuar", margin: EdgeInsets.only(left: 49.h, right: 52.h, bottom: 59.v), buttonStyle: CustomButtonStyles.outlineBlackTL151, onPressed: () {onTapContinueButton(context);}); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the userdatafiveScreen when the action is triggered.
onTapContinueButton(BuildContext context) { Navigator.pushNamed(context, AppRoutes.userdatafiveScreen); } 
 }
