import 'package:flutter/material.dart';import 'package:gymcito/core/app_export.dart';import 'package:gymcito/widgets/app_bar/appbar_subtitle_two.dart';import 'package:gymcito/widgets/app_bar/custom_app_bar.dart';import 'package:gymcito/widgets/custom_elevated_button.dart';import 'package:gymcito/widgets/custom_icon_button.dart';import 'package:gymcito/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class Iphone1415ProEightysevenScreen extends StatelessWidget {Iphone1415ProEightysevenScreen({Key? key}) : super(key: key);

TextEditingController sendAMessagePromptController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 16.v), Padding(padding: EdgeInsets.only(left: 27.h, right: 39.h), child: _buildMessage(context, messageText: "¡Hola, soy FitBot! 👋 Soy tu asistente personal en deportes. ¿En qué puedo ayudarte?")), SizedBox(height: 16.v), _buildMuestrameUnaRutinaPara(context), SizedBox(height: 15.v), Container(width: 287.h, margin: EdgeInsets.only(left: 25.h, right: 81.h), padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 6.v), decoration: AppDecoration.fillGray5001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder24), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.end, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Align(alignment: Alignment.centerLeft, child: Text("EJERCICIOS PARA ESPALDA(Principiante)", style: CustomTextStyles.labelLargePoppinsPrimary)), SizedBox(height: 7.v), CustomImageView(imagePath: ImageConstant.imgLocationBlueGray10002, height: 4.v, width: 16.h, margin: EdgeInsets.only(right: 7.h)), SizedBox(height: 12.v), _buildRemoConBarra(context), SizedBox(height: 6.v), _buildMquinaDeDorsales(context)])), SizedBox(height: 14.v), _buildMuestrameOtrasOpciones(context), SizedBox(height: 20.v), Padding(padding: EdgeInsets.only(left: 20.h, right: 46.h), child: _buildMessage(context, messageText: "Ok, Como vez estos?")), SizedBox(height: 11.v), Container(margin: EdgeInsets.only(left: 20.h, right: 86.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 2.v), decoration: AppDecoration.fillGray5001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder24), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.end, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("EJERCICIOS PARA ESPALDA(Avanzado)", style: CustomTextStyles.labelLargePoppinsPrimary), SizedBox(height: 7.v), _buildPulldownEnPoleaAlta(context), SizedBox(height: 6.v), _buildPulldownTrasnuca(context)])), SizedBox(height: 4.v), _buildSendAMessagePrompt1(context), SizedBox(height: 23.v), _buildHome(context)])), bottomNavigationBar: _buildBottomBar(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 58.h, leading: Container(height: 23.v, width: 14.h, margin: EdgeInsets.only(left: 44.h, top: 8.v, bottom: 24.v), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 23.v, width: 14.h, alignment: Alignment.center, onTap: () {onTapImgArrowLeft(context);}), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 23.v, width: 14.h, alignment: Alignment.center)])), centerTitle: true, title: AppbarSubtitleTwo(text: "Mie 8:21 AM", margin: EdgeInsets.only(top: 31.v, bottom: 8.v)), actions: [Padding(padding: EdgeInsets.fromLTRB(29.h, 8.v, 29.h, 24.v), child: Column(children: [Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h)))]))]); } 
/// Section Widget
Widget _buildMuestrameUnaRutinaPara(BuildContext context) { return CustomElevatedButton(height: 44.v, width: 237.h, text: "Muestrame una rutina para espalda", margin: EdgeInsets.only(right: 39.h), buttonStyle: CustomButtonStyles.fillGray, buttonTextStyle: CustomTextStyles.labelMediumPoppinsPrimary, alignment: Alignment.centerRight); } 
/// Section Widget
Widget _buildRemoConBarra(BuildContext context) { return CustomElevatedButton(width: 148.h, text: "Remo con barra", margin: EdgeInsets.only(right: 7.h), rightIcon: Container(margin: EdgeInsets.only(left: 6.h), child: CustomImageView(imagePath: ImageConstant.imgFluentdumbbell20regular, height: 20.adaptSize, width: 20.adaptSize)), buttonStyle: CustomButtonStyles.fillPrimaryTL16, buttonTextStyle: CustomTextStyles.labelLargePoppinsBluegray90002); } 
/// Section Widget
Widget _buildMquinaDeDorsales(BuildContext context) { return CustomElevatedButton(width: 152.h, text: "Máquina de dorsales", margin: EdgeInsets.only(right: 7.h), buttonStyle: CustomButtonStyles.fillWhiteA, buttonTextStyle: CustomTextStyles.labelLargePoppinsBluegray90002); } 
/// Section Widget
Widget _buildMuestrameOtrasOpciones(BuildContext context) { return CustomElevatedButton(height: 56.v, width: 180.h, text: "Muestrame otras opciones", margin: EdgeInsets.only(right: 39.h), buttonStyle: CustomButtonStyles.fillPrimaryTL24, buttonTextStyle: CustomTextStyles.bodySmallPoppins, alignment: Alignment.centerRight); } 
/// Section Widget
Widget _buildPulldownEnPoleaAlta(BuildContext context) { return CustomElevatedButton(width: 177.h, text: "Pulldown en polea alta", rightIcon: Container(margin: EdgeInsets.only(left: 6.h), child: CustomImageView(imagePath: ImageConstant.imgFluentdumbbell20regular, height: 20.adaptSize, width: 20.adaptSize)), buttonStyle: CustomButtonStyles.fillPrimaryTL16, buttonTextStyle: CustomTextStyles.labelMediumPoppinsBluegray90002, onPressed: () {onTapPulldownEnPoleaAlta(context);}); } 
/// Section Widget
Widget _buildPulldownTrasnuca(BuildContext context) { return CustomElevatedButton(width: 128.h, text: "Pulldown trasnuca", buttonStyle: CustomButtonStyles.fillWhiteA, buttonTextStyle: CustomTextStyles.labelMediumPoppinsBluegray90002); } 
/// Section Widget
Widget _buildSendAMessagePrompt(BuildContext context) { return CustomTextFormField(controller: sendAMessagePromptController, hintText: "Ingresa un mensaje...", textInputAction: TextInputAction.done, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 20.h, 7.v), child: CustomImageView(imagePath: ImageConstant.imgHiconLinearMicrophone1, height: 24.adaptSize, width: 24.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 41.v)); } 
/// Section Widget
Widget _buildSendAMessagePrompt1(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 61.h), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.customBorderBL48), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 25.v), _buildSendAMessagePrompt(context)])); } 
/// Section Widget
Widget _buildHome(BuildContext context) { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 36.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgHome, height: 43.v, width: 41.h, onTap: () {onTapImgHome(context);}), Spacer(flex: 33), CustomImageView(imagePath: ImageConstant.imgActivityGray50003, height: 27.v, width: 26.h, margin: EdgeInsets.only(top: 8.v, bottom: 7.v), onTap: () {onTapImgActivity(context);}), Spacer(flex: 39), CustomImageView(imagePath: ImageConstant.imgTelevision, height: 32.v, width: 37.h, margin: EdgeInsets.only(top: 3.v, bottom: 7.v)), Spacer(flex: 27), CustomImageView(imagePath: ImageConstant.imgUser, height: 43.v, width: 41.h)]))); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return Container(decoration: BoxDecoration(color: theme.colorScheme.onSecondaryContainer), child: Padding(padding: EdgeInsets.only(bottom: 94.v), child: SizedBox(width: 392.h, child: Divider()))); } 
/// Common widget
Widget _buildMessage(BuildContext context, {required String messageText, }) { return Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 24.v), child: CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(8.h), child: CustomImageView(imagePath: ImageConstant.imgBot))), Expanded(child: Container(margin: EdgeInsets.only(left: 8.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 14.v), decoration: AppDecoration.fillGray10001.copyWith(borderRadius: BorderRadiusStyle.customBorderBL24), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text(messageText, style: CustomTextStyles.bodyLargePoppinsBluegray90002.copyWith(color: appTheme.blueGray90002))])))]); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the iphone1415Pro119Screen when the action is triggered.
onTapPulldownEnPoleaAlta(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone1415Pro119Screen); } 
/// Navigates to the iphone1415ProRutinaPrincipianteTabContainerScreen when the action is triggered.
onTapImgHome(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone1415ProRutinaPrincipianteTabContainerScreen); } 
/// Navigates to the iphone1415ProTenScreen when the action is triggered.
onTapImgActivity(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone1415ProTenScreen); } 
 }
