import 'package:flutter/material.dart';import 'package:gymcito/core/app_export.dart';import 'package:gymcito/widgets/app_bar/custom_app_bar.dart';import 'package:gymcito/widgets/custom_elevated_button.dart';import 'package:gymcito/widgets/custom_icon_button.dart';import 'package:gymcito/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class Iphone1415ProEightysixScreen extends StatelessWidget {Iphone1415ProEightysixScreen({Key? key}) : super(key: key);

TextEditingController textBoxController = TextEditingController();

TextEditingController inputController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(crossAxisAlignment: CrossAxisAlignment.end, children: [Align(alignment: Alignment.center, child: SizedBox(height: 16.v, width: 65.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Text("Mie 8:21 AM", style: theme.textTheme.labelLarge)), Align(alignment: Alignment.center, child: Text("Mie 8:21 AM", style: theme.textTheme.labelLarge))]))), SizedBox(height: 12.v), _buildMessageRow(context), SizedBox(height: 12.v), Container(width: 237.h, margin: EdgeInsets.only(left: 142.h, right: 14.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 12.v), decoration: AppDecoration.fillGray5001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder24), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Text("Que puedes hacer?", style: CustomTextStyles.labelMediumPoppinsPrimary)])), SizedBox(height: 35.v), _buildMessageStack(context), SizedBox(height: 28.v), _buildDIETA(context), SizedBox(height: 10.v), _buildRUTINA(context), Spacer(), _buildSendAMessagePrompt(context), SizedBox(height: 21.v), _buildHomeRow(context)])), bottomNavigationBar: _buildBottomBar(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 58.h, leading: Container(height: 23.v, width: 14.h, margin: EdgeInsets.only(left: 44.h, top: 16.v, bottom: 16.v), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 23.v, width: 14.h, alignment: Alignment.center, onTap: () {onTapImgArrowLeft(context);}), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 23.v, width: 14.h, alignment: Alignment.center)])), actions: [Padding(padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 16.v), child: Column(children: [Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h)))]))]); } 
/// Section Widget
Widget _buildMessageRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 48.h, right: 18.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 72.v), child: CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(8.h), child: CustomImageView(imagePath: ImageConstant.imgBot))), Container(margin: EdgeInsets.only(left: 8.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 13.v), decoration: AppDecoration.fillGray10001.copyWith(borderRadius: BorderRadiusStyle.customBorderBL24), child: Container(width: 251.h, margin: EdgeInsets.only(right: 3.h), child: Text("¡Hola, soy FitBot! 👋 Soy tu asistente personal en deportes. ¿En qué puedo ayudarte?", maxLines: 3, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyLargePoppinsBluegray90002.copyWith(height: 1.50))))])); } 
/// Section Widget
Widget _buildTextBox(BuildContext context) { return Expanded(child: Padding(padding: EdgeInsets.only(left: 8.h), child: CustomTextFormField(controller: textBoxController, hintText: "Selecciona tu opcion:", hintStyle: CustomTextStyles.bodyLargePoppinsBluegray90002, contentPadding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 18.v), borderDecoration: TextFormFieldStyleHelper.fillGrayBL24, fillColor: appTheme.gray10001))); } 
/// Section Widget
Widget _buildMessageStack(BuildContext context) { return Container(height: 61.v, width: 327.h, margin: EdgeInsets.only(right: 18.h), child: Stack(alignment: Alignment.centerRight, children: [CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(8.h), alignment: Alignment.topLeft, child: CustomImageView(imagePath: ImageConstant.imgBot)), Align(alignment: Alignment.centerRight, child: Container(margin: EdgeInsets.only(left: 40.h), padding: EdgeInsets.all(16.h), decoration: AppDecoration.fillGray10001.copyWith(borderRadius: BorderRadiusStyle.customBorderBL24), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 1.v, bottom: 3.v), child: Text("Selecciona tu opcion:", style: CustomTextStyles.bodyLargePoppinsBluegray90002)), CustomImageView(imagePath: ImageConstant.imgArrowDownBlack900, height: 20.v, width: 19.h, margin: EdgeInsets.only(left: 39.h, bottom: 9.v))]))), Align(alignment: Alignment.center, child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 29.v), child: CustomIconButton(height: 32.adaptSize, width: 32.adaptSize, padding: EdgeInsets.all(8.h), child: CustomImageView(imagePath: ImageConstant.imgBot))), _buildTextBox(context)]))])); } 
/// Section Widget
Widget _buildDIETA(BuildContext context) { return CustomElevatedButton(height: 62.v, width: 261.h, text: "DIETA", margin: EdgeInsets.only(right: 36.h), buttonStyle: CustomButtonStyles.none, buttonTextStyle: CustomTextStyles.displayMediumPoppinsPrimary, onPressed: () {onTapDIETA(context);}); } 
/// Section Widget
Widget _buildRUTINA(BuildContext context) { return CustomElevatedButton(height: 62.v, width: 261.h, text: "RUTINA", margin: EdgeInsets.only(right: 35.h), buttonStyle: CustomButtonStyles.none, buttonTextStyle: CustomTextStyles.displayMediumPoppinsPrimary, onPressed: () {onTapRUTINA(context);}); } 
/// Section Widget
Widget _buildInput(BuildContext context) { return CustomTextFormField(controller: inputController, hintText: "Ingresa un mensaje...", textInputAction: TextInputAction.done, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 10.v, 20.h, 10.v), child: CustomImageView(imagePath: ImageConstant.imgHiconLinearMicrophone1, height: 24.adaptSize, width: 24.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 44.v)); } 
/// Section Widget
Widget _buildSendAMessagePrompt(BuildContext context) { return Container(margin: EdgeInsets.only(right: 1.h), padding: EdgeInsets.symmetric(horizontal: 61.h, vertical: 3.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.customBorderBL48), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 16.v), _buildInput(context)])); } 
/// Section Widget
Widget _buildHomeRow(BuildContext context) { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 36.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgHome, height: 43.v, width: 41.h, onTap: () {onTapImgHome(context);}), Spacer(flex: 33), CustomImageView(imagePath: ImageConstant.imgActivityGray50003, height: 27.v, width: 26.h, margin: EdgeInsets.only(top: 8.v, bottom: 7.v), onTap: () {onTapImgActivity(context);}), Spacer(flex: 39), CustomImageView(imagePath: ImageConstant.imgTelevision, height: 32.v, width: 37.h, margin: EdgeInsets.only(top: 3.v, bottom: 7.v)), Spacer(flex: 27), CustomImageView(imagePath: ImageConstant.imgUser, height: 43.v, width: 41.h)]))); } 
/// Section Widget
Widget _buildBottomBar(BuildContext context) { return Container(decoration: BoxDecoration(color: theme.colorScheme.onSecondaryContainer), child: Padding(padding: EdgeInsets.only(bottom: 94.v), child: SizedBox(width: 392.h, child: Divider()))); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the iphone1415Pro121Screen when the action is triggered.
onTapDIETA(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone1415Pro121Screen); } 
/// Navigates to the iphone1415Pro122Screen when the action is triggered.
onTapRUTINA(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone1415Pro122Screen); } 
/// Navigates to the iphone1415ProRutinaPrincipianteTabContainerScreen when the action is triggered.
onTapImgHome(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone1415ProRutinaPrincipianteTabContainerScreen); } 
/// Navigates to the iphone1415ProTenScreen when the action is triggered.
onTapImgActivity(BuildContext context) { Navigator.pushNamed(context, AppRoutes.iphone1415ProTenScreen); } 
 }
