import '../tools_screen/widgets/tools_item_widget.dart';import 'package:flutter/material.dart';import 'package:gymcito/core/app_export.dart';import 'package:gymcito/widgets/app_bar/appbar_leading_image.dart';import 'package:gymcito/widgets/app_bar/custom_app_bar.dart';import 'package:gymcito/widgets/custom_outlined_button.dart';class ToolsScreen extends StatelessWidget {const ToolsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 51.h, vertical: 23.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Align(alignment: Alignment.center, child: SizedBox(width: 195.h, child: RichText(text: TextSpan(children: [TextSpan(text: "Cuantas con ", style: CustomTextStyles.titleLargePoppins), TextSpan(text: "herramientas para entrenar?", style: CustomTextStyles.titleLargePoppinsSecondaryContainer)]), textAlign: TextAlign.center))), SizedBox(height: 30.v), _buildTools(context), Spacer(), SizedBox(height: 2.v), Container(width: 217.h, margin: EdgeInsets.only(left: 31.h, right: 41.h), child: Text("Algunos de estos son equipo de gimnasio(Pesas,aparatos,caminadoras,etc).", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodySmall!.copyWith(height: 1.17)))])), bottomNavigationBar: _buildContinuar(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 44.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 30.h, top: 16.v, bottom: 16.v), onTap: () {onTapArrowLeft(context);}), actions: [Padding(padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 16.v), child: Column(children: [Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h)))]))]); } 
/// Section Widget
Widget _buildTools(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 16.h), child: ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 33.v);}, itemCount: 2, itemBuilder: (context, index) {return ToolsItemWidget();})); } 
/// Section Widget
Widget _buildContinuar(BuildContext context) { return CustomOutlinedButton(text: "Continuar", margin: EdgeInsets.only(left: 50.h, right: 51.h, bottom: 56.v), buttonStyle: CustomButtonStyles.outlineBlackTL22, onPressed: () {onTapContinuar(context);}); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the placesScreen when the action is triggered.
onTapContinuar(BuildContext context) { Navigator.pushNamed(context, AppRoutes.placesScreen); } 
 }
