import 'package:flutter/material.dart';import 'package:gymcito/core/app_export.dart';import 'package:gymcito/widgets/custom_outlined_button.dart';class Iphone1415ProFortytwoScreen extends StatelessWidget {const Iphone1415ProFortytwoScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 51.v), child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 5.v), Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 23.v, width: 14.h, margin: EdgeInsets.only(bottom: 721.v), onTap: () {onTapImgArrowLeft(context);}), Expanded(child: Padding(padding: EdgeInsets.only(left: 6.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.centerRight, child: Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h)))), SizedBox(height: 4.v), Align(alignment: Alignment.centerRight, child: Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h)))), SizedBox(height: 4.v), Align(alignment: Alignment.centerRight, child: Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h)))), SizedBox(height: 70.v), Padding(padding: EdgeInsets.only(left: 38.h), child: RichText(text: TextSpan(children: [TextSpan(text: "Que tan ", style: CustomTextStyles.titleLargePoppins), TextSpan(text: "Activo eres?", style: CustomTextStyles.titleLargePoppinsPrimary)]), textAlign: TextAlign.left)), SizedBox(height: 99.v), CustomImageView(imagePath: ImageConstant.imgImage24, height: 180.adaptSize, width: 180.adaptSize, margin: EdgeInsets.only(left: 55.h)), SizedBox(height: 46.v), Container(width: 199.h, margin: EdgeInsets.only(left: 50.h), child: Text("La mayoria del tiempo estoy sentado", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleMediumSourceSansProWhiteA700)), SizedBox(height: 37.v), Container(margin: EdgeInsets.only(left: 6.h, right: 18.h), padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 10.v), decoration: AppDecoration.fillBluegray90001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder24), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeftLimeA400, height: 23.v, width: 14.h, margin: EdgeInsets.only(top: 1.v)), Padding(padding: EdgeInsets.only(top: 1.v), child: Text("Inactivo(Koala)", style: CustomTextStyles.titleMediumSourceSansProWhiteA700Bold)), CustomImageView(imagePath: ImageConstant.imgArrowRightLimeA400, height: 23.v, width: 15.h, margin: EdgeInsets.only(top: 1.v))])), Spacer(), CustomOutlinedButton(text: "Continuar", margin: EdgeInsets.only(right: 22.h), onPressed: () {onTapContinuar(context);})])))])])))); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the trainingScreen when the action is triggered.
onTapContinuar(BuildContext context) { Navigator.pushNamed(context, AppRoutes.trainingScreen); } 
 }
