import 'package:flutter/material.dart';import 'package:gymcito/core/app_export.dart';import 'package:gymcito/widgets/app_bar/custom_app_bar.dart';import 'package:gymcito/widgets/custom_outlined_button.dart';class UserdatatwoScreen extends StatelessWidget {const UserdatatwoScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 43.h, vertical: 44.v), child: Column(children: [Text("¿Cuál es tu estatura?", style: theme.textTheme.headlineMedium), SizedBox(height: 6.v), Text("Esto nos ayuda a crear tu plan personalizado.", style: CustomTextStyles.labelLargePoppinsWhiteA700), SizedBox(height: 46.v), Text("164", style: CustomTextStyles.headlineMediumOpenSansGray80002), SizedBox(height: 4.v), Text("165", style: CustomTextStyles.displaySmallGray800), SizedBox(height: 8.v), Text("166", style: CustomTextStyles.displayMediumOpenSansWhiteA700), SizedBox(height: 15.v), SizedBox(width: 166.h, child: Divider(color: theme.colorScheme.primary)), SizedBox(height: 4.v), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 72.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, children: [Text("167", style: theme.textTheme.displayLarge), Padding(padding: EdgeInsets.only(left: 7.h, top: 51.v, bottom: 3.v), child: Text("cm", style: CustomTextStyles.bodyLargeOpenSans))]))), SizedBox(height: 14.v), SizedBox(width: 166.h, child: Divider(color: theme.colorScheme.primary)), SizedBox(height: 6.v), Text("168", style: CustomTextStyles.displayMediumOpenSansWhiteA700), SizedBox(height: 9.v), Text("169", style: CustomTextStyles.displaySmallGray800), SizedBox(height: 5.v), Text("170", style: CustomTextStyles.headlineMediumOpenSansGray80002), SizedBox(height: 9.v)])), bottomNavigationBar: _buildContinuar(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: Container(height: 24.v, width: 15.h, margin: EdgeInsets.fromLTRB(30.h, 16.v, 348.h, 16.v), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 24.v, width: 15.h, alignment: Alignment.center, onTap: () {onTapImgArrowLeft(context);}), CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 24.v, width: 15.h, alignment: Alignment.center)]))); } 
/// Section Widget
Widget _buildContinuar(BuildContext context) { return CustomOutlinedButton(height: 71.v, text: "Continuar", margin: EdgeInsets.only(left: 45.h, right: 36.h, bottom: 49.v), buttonStyle: CustomButtonStyles.outlineBlackTL151, onPressed: () {onTapContinuar(context);}); } 

/// Navigates back to the previous screen.
onTapImgArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the userdatathreeScreen when the action is triggered.
onTapContinuar(BuildContext context) { Navigator.pushNamed(context, AppRoutes.userdatathreeScreen); } 
 }
