import 'package:flutter/material.dart';import 'package:gymcito/core/app_export.dart';import 'package:gymcito/widgets/custom_elevated_button.dart';import 'package:gymcito/widgets/custom_outlined_button.dart';class HomeScreen extends StatelessWidget {const HomeScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 48.h, vertical: 68.v), decoration: AppDecoration.fillGray, child: Column(mainAxisAlignment: MainAxisAlignment.end, children: [Spacer(), SizedBox(height: 273.v, width: 283.h, child: Stack(alignment: Alignment.bottomCenter, children: [CustomImageView(imagePath: ImageConstant.imgImage8, height: 273.v, width: 260.h, alignment: Alignment.centerLeft), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(bottom: 54.v), child: Text("GYM - SPOT", style: CustomTextStyles.displayMediumPoppinsWhiteA700)))])), SizedBox(height: 13.v), SizedBox(height: 19.v, width: 285.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Text("Actions don't happen without intent", style: CustomTextStyles.bodyLargePoppins)), Align(alignment: Alignment.center, child: Text("Actions don't happen without intent", style: CustomTextStyles.bodyLargePoppins))])), SizedBox(height: 34.v), Align(alignment: Alignment.centerLeft, child: Container(height: 99.v, width: 223.h, margin: EdgeInsets.only(left: 31.h), child: Stack(alignment: Alignment.bottomCenter, children: [_buildSignUpButton(context), _buildLoginButton(context), Align(alignment: Alignment.topCenter, child: Column(mainAxisSize: MainAxisSize.min, children: [_buildFiveButton(context), SizedBox(height: 21.v), Text("Login", style: CustomTextStyles.titleLargePoppins22)]))]))), SizedBox(height: 10.v), _buildLoginWithGoogleButton(context), SizedBox(height: 78.v), Text("Olvidaste tu Contraseña?", style: CustomTextStyles.bodyMediumPoppins)]))))); } 
/// Section Widget
Widget _buildSignUpButton(BuildContext context) { return CustomElevatedButton(height: 44.v, width: 223.h, text: "Sign Up", buttonStyle: CustomButtonStyles.fillPrimary, buttonTextStyle: CustomTextStyles.titleLargePoppins22, onPressed: () {onTapSignUpButton(context);}, alignment: Alignment.topCenter); } 
/// Section Widget
Widget _buildLoginButton(BuildContext context) { return CustomOutlinedButton(height: 44.v, width: 223.h, text: "Login", buttonStyle: CustomButtonStyles.outlineBlack, buttonTextStyle: CustomTextStyles.titleLargePoppins22, onPressed: () {onTapLoginButton(context);}, alignment: Alignment.bottomCenter); } 
/// Section Widget
Widget _buildFiveButton(BuildContext context) { return CustomElevatedButton(height: 44.v, text: "Sign Up", buttonStyle: CustomButtonStyles.fillPrimary, buttonTextStyle: CustomTextStyles.titleLargePoppins22); } 
/// Section Widget
Widget _buildLoginWithGoogleButton(BuildContext context) { return CustomOutlinedButton(height: 49.v, text: "Login with Google", margin: EdgeInsets.only(left: 36.h, right: 43.h), leftIcon: Container(margin: EdgeInsets.only(right: 16.h), child: CustomImageView(imagePath: ImageConstant.imgGoogle, height: 24.adaptSize, width: 24.adaptSize)), buttonStyle: CustomButtonStyles.outlinePrimary, buttonTextStyle: CustomTextStyles.bodyMediumABeeZeeGray5002); } 
/// Navigates to the singupScreen when the action is triggered.
onTapSignUpButton(BuildContext context) { Navigator.pushNamed(context, AppRoutes.singupScreen); } 
/// Navigates to the loginScreen when the action is triggered.
onTapLoginButton(BuildContext context) { Navigator.pushNamed(context, AppRoutes.loginScreen); } 
 }
