import 'package:flutter/material.dart';import 'package:gymcito/core/app_export.dart';import 'package:gymcito/widgets/app_bar/appbar_leading_image.dart';import 'package:gymcito/widgets/app_bar/custom_app_bar.dart';import 'package:gymcito/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class Iphone1415ProFiftyScreen extends StatelessWidget {Iphone1415ProFiftyScreen({Key? key}) : super(key: key);

TextEditingController nameController = TextEditingController();

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 8.v), child: Column(children: [_buildGymSpottRow(context), SizedBox(height: 8.v), _buildNameStack(context), Divider(color: appTheme.black900), SizedBox(height: 18.v), Padding(padding: EdgeInsets.only(left: 22.h, right: 29.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Text("Categorias", style: CustomTextStyles.titleSmallSecondaryContainer_1), Spacer(), SizedBox(height: 21.v, width: 23.h, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgIconHeart, height: 21.v, width: 23.h, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgIconHeartRedA200, height: 21.v, width: 23.h, alignment: Alignment.center)])), Padding(padding: EdgeInsets.only(left: 2.h), child: Text("2", style: CustomTextStyles.titleSmallSecondaryContainer_1))])), SizedBox(height: 23.v), CustomImageView(imagePath: ImageConstant.imgImage10, height: 319.v, width: 312.h, radius: BorderRadius.circular(8.h)), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(left: 25.h, right: 33.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgEdit, height: 24.v, width: 23.h), Spacer(), CustomImageView(imagePath: ImageConstant.imgIconMessageCircle, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 1.v)), CustomImageView(imagePath: ImageConstant.imgIconThumbsUp, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 14.h, top: 1.v)), CustomImageView(imagePath: ImageConstant.imgIconThumbsDown, height: 24.v, width: 23.h, margin: EdgeInsets.only(left: 14.h, top: 1.v))])), SizedBox(height: 7.v), _buildJenniferColumn(context), SizedBox(height: 5.v)]))), bottomNavigationBar: _buildEsteEspacioServiraColumn(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 44.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 30.h, top: 16.v, bottom: 16.v), onTap: () {onTapArrowLeft(context);}), actions: [Padding(padding: EdgeInsets.symmetric(horizontal: 29.h, vertical: 16.v), child: Column(children: [Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h))), SizedBox(height: 4.v), Container(height: 5.v, width: 30.h, decoration: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(2.h)))]))]); } 
/// Section Widget
Widget _buildGymSpottRow(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 3.h, right: 6.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 3.v, bottom: 2.v), child: Text("Gym - Spott", style: CustomTextStyles.titleLargeSourceSansProGray50)), Container(padding: EdgeInsets.symmetric(horizontal: 9.h), decoration: AppDecoration.fillGray700.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgIconRotateCw, height: 18.adaptSize, width: 18.adaptSize, margin: EdgeInsets.only(top: 7.v, bottom: 8.v)), Padding(padding: EdgeInsets.only(left: 12.h), child: SizedBox(height: 34.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: appTheme.black900, indent: 1.h))), SizedBox(height: 34.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: appTheme.black900, indent: 1.h)), CustomImageView(imagePath: ImageConstant.imgIconLink, height: 21.v, width: 22.h, margin: EdgeInsets.only(left: 10.h, top: 7.v, bottom: 6.v)), Padding(padding: EdgeInsets.only(left: 11.h), child: SizedBox(height: 34.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: appTheme.black900, indent: 1.h))), CustomImageView(imagePath: ImageConstant.imgIconMail, height: 18.v, width: 17.h, margin: EdgeInsets.only(left: 14.h, top: 10.v, bottom: 6.v)), Padding(padding: EdgeInsets.only(left: 16.h), child: SizedBox(height: 34.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: appTheme.black900, indent: 1.h))), CustomImageView(imagePath: ImageConstant.imgIconMoreVertical, height: 24.v, width: 23.h, margin: EdgeInsets.only(left: 8.h, top: 7.v, bottom: 3.v))]))])); } 
/// Section Widget
Widget _buildNameStack(BuildContext context) { return SizedBox(height: 60.v, width: 353.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topLeft, child: Container(height: 22.v, width: 74.h, margin: EdgeInsets.only(left: 40.h, top: 15.v), child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Text("Elements", style: theme.textTheme.bodyLarge)), Align(alignment: Alignment.center, child: SizedBox(height: 22.v, width: 74.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Text("Elements", style: theme.textTheme.bodyLarge)), Align(alignment: Alignment.center, child: SizedBox(height: 22.v, width: 74.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.center, child: Text("Elements", style: theme.textTheme.bodyLarge)), Align(alignment: Alignment.center, child: Text("Elements", style: theme.textTheme.bodyLarge))])))])))]))), CustomTextFormField(width: 352.h, controller: nameController, hintText: "NameUser1922", textInputAction: TextInputAction.done, alignment: Alignment.center, contentPadding: EdgeInsets.symmetric(horizontal: 19.h, vertical: 20.v), borderDecoration: TextFormFieldStyleHelper.fillPrimary, fillColor: theme.colorScheme.primary), Align(alignment: Alignment.topCenter, child: SizedBox(width: 352.h, child: Divider(color: appTheme.black900)))])); } 
/// Section Widget
Widget _buildJenniferColumn(BuildContext context) { return Container(margin: EdgeInsets.only(left: 20.h, right: 17.h), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 5.v), decoration: AppDecoration.fillGray700.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [Text("Jennifer", style: CustomTextStyles.titleSmallSecondaryContainer_1), SizedBox(height: 9.v), SizedBox(width: 292.h, child: Text("Este espacio servira para comentarios sobre las rutinas o ayudar a usuarios con dudas,tal como un foro", maxLines: 3, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumSourceSansProGray50.copyWith(height: 1.14))), SizedBox(height: 1.v)])); } 
/// Section Widget
Widget _buildEsteEspacioServiraColumn(BuildContext context) { return Container(margin: EdgeInsets.only(left: 50.h, right: 50.h, bottom: 53.v), decoration: AppDecoration.fillGray700.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: SizedBox(width: 292.h, child: Text("Este espacio servira para comentarios sobre las rutinas o ayudar a usuarios con dudas,tal como un foro", maxLines: 3, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumSourceSansProGray50.copyWith(height: 1.14)))); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
